import {
  IsString, IsOptional, IsEnum, IsUUID, IsInt, IsBoolean, IsEmail,
  MaxLength, Min, Max,
} from 'class-validator';
import { Type } from 'class-transformer';
import {
  ConversationStatus,
  ConversationPriority,
  ConversationType,
  ConversationCategory,
} from '@prisma/client';

/* ═══════════════════════════════════════
   Create Chat DTO (real-time)
   ═══════════════════════════════════════ */

/**
 * Creates a new CHAT conversation.
 *
 * Chats are:
 *   - Real-time (WebSocket)
 *   - Created from the floating widget
 *   - Like WhatsApp — quick, immediate responses
 *   - Can be escalated to a Ticket
 *
 * No category needed (chats are direct communication).
 *
 * Ref: DECISIONS.md §9, §43
 */
export class CreateChatDto {
  @IsString()
  @MaxLength(500)
  subject: string;

  @IsString()
  @MaxLength(10000)
  body: string;

  @IsOptional()
  @IsUUID()
  service_id?: string;
}

/* ═══════════════════════════════════════
   Create Guest Chat DTO (anonymous — no JWT)
   ═══════════════════════════════════════ */

/**
 * Creates a new CHAT conversation for an anonymous visitor.
 *
 * Guest chats are:
 *   - Created from the landing page (no account required)
 *   - Identified by a guest_session_token stored in HttpOnly cookie
 *   - guest_name is required (displayed in the chat bubble)
 *   - guest_email is optional (enables automatic linking when the visitor registers — 7.5.1)
 *   - Rate limited: 3 chats/hour per IP, 10 messages/minute per session (7.4.3)
 *   - The guest_session_token hash is stored in conversations.guest_session_hash
 *
 * Ref: ROADMAP.md 7.4.1-7.4.2, DECISIONS.md §38, DATABASE_SCHEMA.md
 */
export class CreateGuestChatDto {
  @IsString()
  @MaxLength(200)
  guest_name: string;

  @IsOptional()
  @IsEmail()
  @MaxLength(255)
  guest_email?: string;

  @IsString()
  @MaxLength(10000)
  body: string;
}

/* ═══════════════════════════════════════
   Create Ticket DTO (asynchronous)
   ═══════════════════════════════════════ */

/**
 * Creates a new TICKET (caso).
 *
 * Tickets are:
 *   - Asynchronous (like Gmail/email)
 *   - For complex problems requiring traceability
 *   - For "We Do It For You" communication
 *   - Categorized for organization
 *
 * Ref: DECISIONS.md §9, §43
 */
export class CreateTicketDto {
  @IsString()
  @MaxLength(500)
  subject: string;

  @IsString()
  @MaxLength(10000)
  body: string;

  @IsOptional()
  @IsEnum(ConversationPriority)
  priority?: ConversationPriority;

  @IsEnum(ConversationCategory)
  category: ConversationCategory;

  @IsOptional()
  @IsUUID()
  service_id?: string;
}

/* ═══════════════════════════════════════
   Create Message DTO
   ═══════════════════════════════════════ */

/**
 * Adds a message to an existing conversation (chat or ticket).
 *
 * sender_type and sender_id are set by the controller based on JWT:
 *   - client → sender_type=client, sender_id=user.id
 *   - agent  → sender_type=agent, sender_id=user.id
 *   - system → sender_type=system (generated by events)
 *
 * is_internal: only visible to agents. Used for internal notes.
 * Ref: DECISIONS.md §9
 */
export class CreateMessageDto {
  @IsString()
  @MaxLength(10000)
  body: string;

  @IsOptional()
  attachments?: any;

  /**
   * Internal messages are only visible to agents.
   * Clients never see is_internal=true messages.
   */
  @IsOptional()
  @IsBoolean()
  is_internal?: boolean;
}

/* ═══════════════════════════════════════
   Update Conversation DTO
   ═══════════════════════════════════════ */

/**
 * Update conversation metadata (applicable to both chats and tickets).
 * Used by agents/admin to manage conversations.
 * Status changes trigger specific business logic (see SupportService).
 */
export class UpdateConversationDto {
  @IsOptional()
  @IsEnum(ConversationStatus)
  status?: ConversationStatus;

  @IsOptional()
  @IsEnum(ConversationPriority)
  priority?: ConversationPriority;

  @IsOptional()
  @IsEnum(ConversationCategory)
  category?: ConversationCategory;

  @IsOptional()
  @IsUUID()
  assigned_agent_id?: string;

  @IsOptional()
  @IsString()
  @MaxLength(5000)
  resolution_note?: string;

  @IsOptional()
  tags?: any;
}

/* ═══════════════════════════════════════
   Conversation List Query DTO
   ═══════════════════════════════════════ */

/**
 * Query parameters for listing conversations.
 * `type` is set by the controller based on the endpoint (/chats or /tickets).
 * It's optional in the DTO to avoid validation conflicts — the controller always overrides it.
 * Agents see all conversations (optionally filtered).
 * Clients only see their own (enforced by controller, not DTO).
 */
export class ConversationListQueryDto {
  @IsOptional()
  @IsEnum(ConversationType)
  type?: ConversationType;

  @IsOptional()
  @IsInt()
  @Min(1)
  @Type(() => Number)
  page?: number;

  @IsOptional()
  @IsInt()
  @Min(1)
  @Max(100)
  @Type(() => Number)
  limit?: number;

  @IsOptional()
  @IsEnum(ConversationStatus)
  status?: ConversationStatus;

  @IsOptional()
  @IsEnum(ConversationPriority)
  priority?: ConversationPriority;

  @IsOptional()
  @IsEnum(ConversationCategory)
  category?: ConversationCategory;

  @IsOptional()
  @IsUUID()
  assigned_agent_id?: string;

  @IsOptional()
  @IsUUID()
  user_id?: string;

  @IsOptional()
  @IsString()
  channel?: string;

  @IsOptional()
  @IsString()
  search?: string;
}

/* ═══════════════════════════════════════
   Escalate Chat to Ticket DTO
   ═══════════════════════════════════════ */

/**
 * Escalates a chat to a ticket.
 * The chat history is copied as unified context to the new ticket.
 * The original chat remains but can be closed.
 *
 * Ref: DECISIONS.md §9, §43
 */
export class EscalateToTicketDto {
  @IsOptional()
  @IsString()
  @MaxLength(500)
  subject?: string; // Optional override, defaults to chat subject

  @IsEnum(ConversationCategory)
  category: ConversationCategory;

  @IsOptional()
  @IsEnum(ConversationPriority)
  priority?: ConversationPriority;

  @IsOptional()
  @IsString()
  @MaxLength(5000)
  agent_notes?: string; // Additional context from the agent
}
